version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - envi.env
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.landing-page.entrypoints=web,websecure'
      - 'traefik.http.routers.landing-page.rule=Host(`api.louislecouturier.fr`)'
      - 'traefik.http.routers.landing-page.tls=true'
      - 'traefik.http.routers.landing-page.tls.certresolver=production'
    networks:
      - 'traefik_default'

networks:
  traefik_default:
    external: true